name: Build and Notify

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.13' # Specify the Node.js version you need

    - name: Install Angular CLI
      run: npm install -g @angular/cli
      
    - name: Install Dependencies
      run: npm install

    - name: Build
      run: ng build
      # This now should work as Angular CLI is installed globally
        
    - name: Send Email Notification on Failure
      if: failure()
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp-mail.outlook.com
        server_port: 587
        username: ${{ secrets.EMAIL_USERNAME }}
        password: ${{ secrets.EMAIL_PASSWORD }}
        subject: Build Failure Notification
        body: The build failed for ${{ github.repository }}. Please check the actions log for more details.
        to: khaled.maati@accenture.com
        from: zutrzuturztfuztfu@outlook.com
        content_type: text/plain
        
        # EMAIL_USERNAME(zutrzuturztfuztfu@outlook.com)
        # EMAIL_PASSWORD(@igcdkzudsagdi)
        
