name: Build and Notify

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Dependencies
      run: npm install
    - name: Build
      run: ng build --prod
      # Replace "npm run build-prod" with your actual build command

    - name: Check Build Success
      if: failure() # This step will run only if the previous step fails
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: smtp.example.com
        server_port: 465
        username: ${{secrets.EMAIL_USERNAME}}
        password: ${{secrets.EMAIL_PASSWORD}}
        subject: Build Failed
        # Customize the body as needed
        body: The production build failed. Please check the GitHub Actions logs for more details.
        to: khaled.maati@accenture.com
        from: GitHub Actions <noreply@github.com>
