name: Update Version Info

on: push

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
            token: ${{ secrets.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 }} # Use the PAT you stored as a secret

      - name: Update version.json
        run: |
          echo "{\"commitHash\": \"$(git rev-parse HEAD)\", \"commitMessage\": \"$(git log -1 --pretty=%B)\"}" > src\assets\git-info.json

      - name: Commit and Push
        run: |
        
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add src\assets\git-info.json
          git commit -m "Update version.json with latest Git info" || echo "No changes to commit"
          git push
