name: Update Git Info

on:
  push:

jobs:
  update-git-info:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        repo-token: ${{ secrets.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 }}
        
    - name: Generate Git Info
      run: |
        echo '{ "commitHash": "'$(git rev-parse HEAD)'", "date": "'$(date)'"}' > src/assets/git-info.json

    - name: Commit and Push
      env:
        PERSONAL_ACCESS_TOKEN: ${{ secrets.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 }}
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add src/assets/git-info.json
        git commit -m "Update Git Info"
        git push https://x-access-token:${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}@github.com/khaledmaati/uberEats.git
