on:
  push:

jobs:
  update-git-info:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
<<<<<<< HEAD
=======
      with:
        fetch-depth: 0 # Ensure we have the full history for amend

>>>>>>> 6a6c133c8aa80cee9194a6669c3b87be09d47b94

    - name: Generate Git Info
      run: |
        echo '{ "commitHash": "'$(git rev-parse HEAD)'", "date": "'$(date)'"}' > src/assets/git-info.json

    - name: Commit and Push
      run: |
        git config --global user.email "khaled.maati@accenture.com"
        git config --global user.name "khaled maati"

        git add src/assets/git-info.json
<<<<<<< HEAD
        git commit -m "Update Git Info"
        git push

=======
        # git commit -m "Update Git Info"
        # git push

        # Amend the existing commit
        # git commit --amend --no-edit # Keeps the same commit message

        # After amending your commit
        # git push


        # Amending the commit without changing its commit message
        git commit --amend --no-edit 
        # Force push is required to update the commit on remote. Use with caution!
        git push --force-with-lease
>>>>>>> 6a6c133c8aa80cee9194a6669c3b87be09d47b94
